name: CNT Monitor
on:
  schedule:
    - cron: '0 */3 * * *'    # cada 3 h, todos los días (UTC)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: |
          python -m pip install -U pip
          pip install requests beautifulsoup4 python-dotenv
      - run: python cnt_monitor.py
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
