name: CNT Monitor

on:
  schedule:
    # ── minuto 0, cada 3 h, todos los días (UTC) ──
    - cron: '0 */3 * * *'
  workflow_dispatch:        # botón “Run workflow”

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Clona el repositorio
        uses: actions/checkout@v4

      - name: Configura Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instala dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 python-dotenv

      - name: Ejecuta el monitor CNT
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python cnt_monitor.py
